# Generated by Django 3.0.2 on 2021-05-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
